# Workflow to build and deploy to your GitHub Pages repo.

name: Github Pages Bloomberg



env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_LIVESTREAM_WEBHOOK }}
  DB_NAME: ${{ secrets.PSCALE_DB_NAME }}
  DB_USER: ${{ secrets.PSCALE_DB_USER }}
  DB_HOST: ${{ secrets.PSCALE_DB_HOST }}
  DB_PASSWORD: ${{ secrets.PSCALE_DB_PASSWORD }}

on:
  # Triggers the workflow on push and pull request events but only for the main branch
  push:
    branches: [main, feature/*]

  schedule:
    # Runs at 22:30 UTC every day
    - cron: '30 23 * * *' # Runs at 23:30 UTC every day

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.6

      - name: Install python Dependencies
        run: |
          python -m pip install -r py_server/requirements.txt
      # install dependenices
      # Install dependencies with npm
      - name: Install npm dependencies
        run: cd website && npm install

      - name: Get data from pscale  
        run: cd website && python mk_pages.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config pull.rebase false
          git pull origin main
          git add *.csv
          git add data/**/*.csv
          git commit -m "add files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


      # Build the project and add .nojekyll file to supress default behaviour
      - name: Build
        run: |
          cd website
          npm run build
          touch ./dist/.nojekyll
      # Push to your pages repo
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: website/dist # The folder the action should deploy.